Lessons list
quranacademy/arabic-alphabet pull request #3
Opened 2021-03-11 17:45 UTC by Threetifal

2021-03-11 20:04 UTC, Imangazaliev requested changes

2021-03-11 20:04 UTC, Imangazaliev commented on views/LessonsBlockList/index.tsx
> +    let idX = 0;
Эта переменная не нужна, тем более она нигде не изменяется.

2021-03-11 20:04 UTC, Imangazaliev commented on views/LessonsBlockList/index.tsx
> +                            key={item.id}
1. В качестве `key` используй `orderNumber`, он ведь уникален.
2. Пропсы лучше сортировать по алфавиту.

2021-03-11 20:04 UTC, Imangazaliev commented on views/LessonsBlockList/LessonsList/LessonsList.module.scss
> +.listBlock {
Этот файл тоже лучше назвать `Course.module.scss` и убрать ненужный префикс "list" у классов.

2021-03-12 14:37 UTC, Threetifal commented on pages/lists.ts
> +export { LessonsBlockList as default } from "~/views/LessonsBlockList";
Готово

2021-03-12 14:40 UTC, Threetifal commented on views/LessonsBlockList/LessonsList/index.tsx
> +import styles from "./LessonsList.module.scss";
Готово

2021-03-12 16:30 UTC, Threetifal commented on views/LessonsBlockList/LessonsList/index.tsx
> +    orderNumber: number;
Не получается :Д

2021-03-12 16:31 UTC, Threetifal commented on views/LessonsBlockList/index.tsx
> +import { Layout } from "~/components";
Готово

2021-03-12 16:32 UTC, Threetifal commented on views/LessonsBlockList/index.tsx
> +    const lessonsList = [
قد تم

2021-03-12 16:32 UTC, Threetifal commented on views/LessonsBlockList/index.tsx
> +    let idX = 0;
Она сама убежала

2021-03-12 17:04 UTC, closed without merging